### ISSUE TITLE
Custom parameters to EvoSuite

### ISSUE THREAD

**Issue by jzelenjak** [ciselab/TestGenie#1]
# Description
As a developer, I should be able to use a `Settings` menu for the plugin, where I can set parameters such as `Algorithms` and `Population`, so that I can easily specify custom parameters where I want and leave the default ones I do not want to modify.

This issue has been modified to account for the new client requirements, which is reordering the options in the currently existing Settings menu.

# Definition of Done
* [ ]  Parameters are categorised. Either there are tabs or it is a list with headings
* [ ]  There is an option to modify the parameters
* [ ]  There is a certain boundary on the parameters, so that a developer cannot set unreasonable parameter values (e.g 1000h on running time)
* [ ]  EvoSuite can run with the specified parameters

**Comment by lyuben-todorov** [comment]
> There is a certain boundary on the parameters, so that a developer cannot set unreasonable parameter values (e.g 1000h on running time)

Shouldn't that be left to user discretion? We cannot really decide what are meaningful values for everything, however we can give ranges to certain variables whose range we know, such as probabilities [0,1] and enumration options:
```
Search algorithm (Possible values: [RANDOM_SEARCH, STANDARD_GA, MONOTONIC_GA, STEADY_STATE_GA, BREEDER_GA, CELLULAR_GA, STANDARD_CHEMICAL_REACTION, ONE_PLUS_LAMBDA_LAMBDA_GA, ONE_PLUS_ONE_EA, MU_PLUS_LAMBDA_EA, MU_LAMBDA_EA, MOSA, LIPS, MIO, NSGAII, SPEA2])

```
