### ISSUE TITLE
Make plugin settings project level

### ISSUE THREAD

**Issue by jzelenjak** [ciselab/TestGenie#144]
**Describe the bug**
At the moment, application services and application configurables are sometimes confused. For example, our Settings and Quick Access Parameters are application level. The problem is that sometimes it is undesired, for example, in case of telemetry path that has to be project-specific.

**To Reproduce**
0. Open two projects
1. Go to 'Settings' in one of the projects
2. Click on 'Telemetry Path' text area
3. Specify a path, press Apply and OK to close
4. Open 'Settings' in another project
5. Observe that the path is the same as in the other project, even though it has to be different

**Expected behavior**
Parameters in the Plugin Settings page have to be project-specific.

In addition, settins service has to be splitted into `SettingsProjectService`, `SettingsApplicationService`, `SettingsProjectState`, `SettingsApplicationState`.

**Screenshots**

**Additional context**

**Comment by martinmladenov** [comment]
Things like build command and classpath should also ideally be project-specific.

**Comment by jzelenjak** [comment]
> Things like build command and classpath should also ideally be project-specific.
Yes, i agree
