### ISSUE TITLE
Set up the link between EvoSuite and the plugin

### ISSUE THREAD

**Issue by martinmladenov** [ciselab/TestGenie#15]
# Description
Create basic integration between EvoSuite and the plugin

# Definition of Done
* [ ]  Make it possible to generate tests for a (hardcoded) class from the plugin (i.e. execute the same functionality that a command such as `java -jar evosuite-1.2.0.jar -projectCP target/classes/ -class delft.ArrayUtils` would have)
* [ ] Resolve any issues such as Java version or dependency incompatibilities that would prevent this integration from working

**Comment by martinmladenov** [comment]
Moving this issue from Sprint 0 to Sprint 1 due to the issues that occurred while working on it.

**Comment by lyuben-todorov** [comment]
Tracked in #18
