### ISSUE TITLE
Transfer all hard-coded strings to xml files

### ISSUE THREAD

**Issue by kirilvasilev16** [ciselab/TestGenie#162]
# Description
Transfer all labels, messages and predefined values to separate xml files for the purpose of extensibility to allow easier translation of the strings.

# Definition of Done
* [ ]  Move all messages to xml file
* [ ]  Move all labels texts to xml file
* [ ]  Move all settings predefined values to a separate xml file

**Comment by jzelenjak** [comment]
We do have two bundle classes: for messages and for defaults. What is wrong with them?
