### ISSUE TITLE
Providing jar

### ISSUE THREAD

**Issue by jzelenjak** [ciselab/TestGenie#3]
# Description
As a developer, I should be able to have the option to provide an EvoSuite jar executable to my plugin through a settings menu, so that I can actually use the plugin.

# Definition of Done
* [ ]  There is a `Setting` menu for selecting a jar executable
* [ ]  The jar can be used to running EvoSuite

**Comment by martinmladenov** [comment]
Closing as this issue is a duplicate of #49.
