### ISSUE TITLE
Implement tests for the code base

### ISSUE THREAD

**Issue by SergeyDatskiv** [ciselab/TestGenie#39]
# Description
Implement UI tests for the code to ensure the quality/functionality of the plugin and code. 

# Definition of Done
* [x]  Do you have tests that test the UI of the plugin? 

Possible sections to test:
- Settings 
- Quick Access Tool Window 
- Tool Window coverage visualization
- Test selection window  

* [x] Have you considered writing tests not just for UI?   
* [x]  Can the tests run on GitHub actions?

**Comment by kirilvasilev16** [comment]
Closed by PR #43
