### ISSUE TITLE
Option to provide an EvoSuite jar

### ISSUE THREAD

**Issue by martinmladenov** [ciselab/TestGenie#49]
# Description
*As a developer, I should be able to have the option to provide an EvoSuite jar executable to my plugin through a settings menu, so that I can actually use the plugin.*

# Definition of Done
* [ ] In the settings menu, there is an option to provide a path to an evosuite jar file
* [ ] To make it easier for the user to provide the path, a file chooser is shown when entering a path
* [ ] The file path is used when invoking EvoSuite
* [x] Hardcoded references are removed

**Comment by martinmladenov** [comment]
This should be discussed with the client. Currently, this feature may be unnecessary and may only confuse users.

**Comment by jzelenjak** [comment]
Closed after discussing it in the client meeting in week 4
