### ISSUE TITLE
Generated tests tool window shows syntax errors

### ISSUE THREAD

**Issue by martinmladenov** [ciselab/TestGenie#55]
**Describe the bug**
When the generated tests tool window is updated, it shows an "Unexpected tokens" syntax error over all tests.

**To Reproduce**
1. Generate tests for a class or a method
2. Open a different tool window alongside TestGenie's (e.g. the Maven tool window)
3. Look at the syntax errors and red underlining in the generated test text boxes

**Expected behavior**
No syntax errors are shown

**Screenshots**
![image](https://user-images.githubusercontent.com/30376060/168027852-f5c720b7-e73c-49b9-a203-eb60ca623c68.png)

**Comment by SergeyDatskiv** [comment]
Useful links for this issue [JetBrains TextEditorField Doc](https://plugins.jetbrains.com/docs/intellij/editor-components.html#editortextfield)
