### ISSUE TITLE
Testing PSI selection

### ISSUE THREAD

**Issue by jzelenjak** [ciselab/TestGenie#71]
# Description
Write tests for PSI selection (classes, methods and lines). Verify that only the classes that are supposed to be selected are selected, only the methods that are supposed to be selected are selected and only the lines that are supposed to be selected are selected.

# Definition of Done
* [x]  Class selection is tested
* [x]  Only the allowed classes are selected
* [x]  Method selection is tested
* [x]  Only the allowed methods are selected
* [x]  Line selection is tested
* [x]  Only the allowed lines are selected

**Comment by martinmladenov** [comment]
Moving to Sprint 4
