### ISSUE TITLE
UI Testing for Coverage Visualisation

### ISSUE THREAD

**Issue by kirilvasilev16** [ciselab/TestGenie#75]
# Description
Test the Coverage Visualisation offered by TestGenie.

# Definition of Done
* [x]  Test coverage visualisation is generated when tests are generated.
* [x]  Test a new toolWindow tab is created.
* [x]  Test the table in coverage visualisation tab has correct data.
* [x]  ~~Test (if possible) that the gutter is working properly.~~ Turned out impossible, because IntelliJ does not support tests for gutter.
* [x]  ~~Test (if possible) that the gutter hyperlinks are working properly.~~ Turned out impossible, because IntelliJ does not support tests for gutter.

**Comment by martinmladenov** [comment]
Moving to Sprint 4
