### ISSUE TITLE
Interactive learning

### ISSUE THREAD

**Issue by kirilvasilev16** [ciselab/TestGenie#8]
# Description
As a developer, I could be able to conduct interactive learning via TestGenie using gathered feedback (e.g provide a proper string format (e.g regex) if the test generator used a wrong string format), so that it can be passed to the EvoSuite application in order to improve the quality and efficiency of the next generated tests.

**UPDATE: after implementing the new features introduced by the client and having a discussion, it has been decided that our part of this issue is going to be implementing telemetry diff**

Depends on #6 #10 

# Definition of Done
* [x]  After modifying and applying the tests, if the telemetry option has been enabled, changes made in tests are identified and stored in a separate file
* [x] The functionality is integrated with already existing telemetry collection

**Comment by martinmladenov** [comment]
This issue has been implemented in #6 and #10. Closing.
