### ISSUE TITLE
Research dynamic background verification of existing tests

### ISSUE THREAD

**Issue by kirilvasilev16** [ciselab/TestGenie#98]
# Description
Research dynamic background verification of existing tests - that is run every test to see if they pass and discard them if they do not.

# Definition of Done
* [x]  Find a way to verify that the generated or cached tests are still passing after code modifications.
* [ ] Write some code that can achieve this.

**Comment by martinmladenov** [comment]
Moving to Sprint 5 as other issues were prioritised by the client this week.

**Comment by lyuben-todorov** [comment]
We've been shown [scripts](**url**) that serve as automation for this. The process would be 
1. Compile a test binary with the appropriate classpath.
2. Have the standalone evosuite runner at hand.
3. Run the test binary with the standalone runner.
